CREATE TABLE login(
	id_login INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(30) NOT NULL,
	senha VARCHAR(30) NOT NULL
);
CREATE TABLE opcoes(
	vagas INT NOT NULL,
	preco_entrada DECIMAL(10,2) NOT NULL,
	preco_hora DECIMAL(10,2) NOT NULL,
	alterado  DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE veiculo(
	id_veiculo INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
	placa VARCHAR(9) NOT NULL,
	marca VARCHAR(30) NOT NULL,
	modelo VARCHAR(30) NOT NULL,
	cor VARCHAR(30) NOT NULL,
	cadastro  DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE movimento(
	id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
	entra DATETIME DEFAULT CURRENT_TIMESTAMP,
	saida DATETIME,
	valor DECIMAL(10,2),
	id_veiculo INT,
	id_login INT,
	CONSTRAINT fk_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id_veiculo),
	CONSTRAINT fk_login FOREIGN KEY (id_login) REFERENCES login(id_login)

);
